
mysql:
  enabled: false
  host: "host"
  port: 3306
  database: "database"
  username: "username"
  password: "password"
  table-prefix: "ariscore_"
  use-ssl: false

sqlite:
  enabled: true

auto-shards:
  enabled: true
  interval: 300
  amount: 10
  permission: "ariscore.shards.auto"
  blocked_worlds: []
  blocked_regions: []

afk-shards:
  enabled: true
  interval: 60
  amount: 5
  permission: "ariscore.shards.afk"
  blocked_worlds: []
  blocked_regions: []

sounds:
  receive:
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 1.0
    pitch: 1.2
  error:
    sound: ENTITY_VILLAGER_NO
    volume: 1.0
    pitch: 1.0

messages:
  give: "&aGave &f{player} &a{amount} &fshards."
  give_ab: "&a+{amount} shards"
  take: "&cTook &f{player} &c{amount} &fshards."
  take_ab: "&c-{amount} shards"
  reset: "&cReset &f{player}&c's shards."
  reset_ab: "&cShards reset"
  auto_receive_ab: "&a+{amount} shards"
  afk_receive_ab: "&a+{amount} shards"
  afk_countdown_ab: "&eNext shards: &f{time}s"
  not_enough: "&cYou don't have enough shards."
  not_enough_ab: "&cNot enough shards"
  player_not_found: "&cPlayer not found."
  no_permission: "&cYou don't have permission."
  give_all: "&aGave everyone &f{amount} &ashards."
  take_all: "&cTook &f{amount} &cshards from everyone."
  reset_all: "&cReset everyone's shards."
  usage: "&cUsage: /shards <give|take|reset> <player|all> [amount]"