auction:
  duration-hours: 24
  fee-percentage: 0
  minimum-price: 1.0
  maximum-price: 1000000000.0
  expire-check-interval: 60

economy:
  currency-format: '#,##0.##'
  abbreviations:
    enabled: true
    formats:
      - K
      - M
      - B
      - T

blacklist-items:
  - BEDROCK
  - BARRIER
  - COMMAND_BLOCK

chat-input:
  use-sign: true
  use-chat: false

sign-lines:
  - ''
  - '↑↑↑↑↑↑↑↑↑↑↑↑↑'
  - '   Search   '
  - ''

sounds:
  click: ui.button.click
  inventory-full: entity.villager.no
  reload: entity.player.levelup
  item-sold: entity.player.levelup
  item-bought: entity.player.levelup
  blacklisted: block.anvil.destroy
